//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavalWarsCliente.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.HelloWorldResponse HelloWorld(NavalWarsCliente.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.insertarUsuarioResponse insertarUsuario(NavalWarsCliente.ServiceReference1.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarArbol", ReplyAction="*")]
        void generarArbol();
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.buscarUsuarioResponse buscarUsuario(NavalWarsCliente.ServiceReference1.buscarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.eliminarUsuarioResponse eliminarUsuario(NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerInfoUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioResponse obtenerInfoUsuario(NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/modificarUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.modificarUsuarioResponse modificarUsuario(NavalWarsCliente.ServiceReference1.modificarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUsuarioNick", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.buscarUsuarioNickResponse buscarUsuarioNick(NavalWarsCliente.ServiceReference1.buscarUsuarioNickRequest request);
        
        // CODEGEN: Generating message contract since element name nickUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addjuegosUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.addjuegosUsuarioResponse addjuegosUsuario(NavalWarsCliente.ServiceReference1.addjuegosUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarJuegosUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioResponse eliminarJuegosUsuario(NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickUsuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ModificarJuegosUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioResponse ModificarJuegosUsuario(NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(NavalWarsCliente.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(NavalWarsCliente.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.insertarUsuarioRequestBody Body;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(NavalWarsCliente.ServiceReference1.insertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int conectado;
        
        public insertarUsuarioRequestBody() {
        }
        
        public insertarUsuarioRequestBody(string nickname, string nombre, string password, string email, int conectado) {
            this.nickname = nickname;
            this.nombre = nombre;
            this.password = password;
            this.email = email;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.insertarUsuarioResponseBody Body;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(NavalWarsCliente.ServiceReference1.insertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarUsuarioResult;
        
        public insertarUsuarioResponseBody() {
        }
        
        public insertarUsuarioResponseBody(bool insertarUsuarioResult) {
            this.insertarUsuarioResult = insertarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.buscarUsuarioRequestBody Body;
        
        public buscarUsuarioRequest() {
        }
        
        public buscarUsuarioRequest(NavalWarsCliente.ServiceReference1.buscarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public buscarUsuarioRequestBody() {
        }
        
        public buscarUsuarioRequestBody(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.buscarUsuarioResponseBody Body;
        
        public buscarUsuarioResponse() {
        }
        
        public buscarUsuarioResponse(NavalWarsCliente.ServiceReference1.buscarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool buscarUsuarioResult;
        
        public buscarUsuarioResponseBody() {
        }
        
        public buscarUsuarioResponseBody(bool buscarUsuarioResult) {
            this.buscarUsuarioResult = buscarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.eliminarUsuarioRequestBody Body;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(NavalWarsCliente.ServiceReference1.eliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public eliminarUsuarioRequestBody() {
        }
        
        public eliminarUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.eliminarUsuarioResponseBody Body;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(NavalWarsCliente.ServiceReference1.eliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool eliminarUsuarioResult;
        
        public eliminarUsuarioResponseBody() {
        }
        
        public eliminarUsuarioResponseBody(bool eliminarUsuarioResult) {
            this.eliminarUsuarioResult = eliminarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerInfoUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerInfoUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioRequestBody Body;
        
        public obtenerInfoUsuarioRequest() {
        }
        
        public obtenerInfoUsuarioRequest(NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerInfoUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public obtenerInfoUsuarioRequestBody() {
        }
        
        public obtenerInfoUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class obtenerInfoUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="obtenerInfoUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioResponseBody Body;
        
        public obtenerInfoUsuarioResponse() {
        }
        
        public obtenerInfoUsuarioResponse(NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class obtenerInfoUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NavalWarsCliente.ServiceReference1.ArrayOfString obtenerInfoUsuarioResult;
        
        public obtenerInfoUsuarioResponseBody() {
        }
        
        public obtenerInfoUsuarioResponseBody(NavalWarsCliente.ServiceReference1.ArrayOfString obtenerInfoUsuarioResult) {
            this.obtenerInfoUsuarioResult = obtenerInfoUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.modificarUsuarioRequestBody Body;
        
        public modificarUsuarioRequest() {
        }
        
        public modificarUsuarioRequest(NavalWarsCliente.ServiceReference1.modificarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nuevoNick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int conectado;
        
        public modificarUsuarioRequestBody() {
        }
        
        public modificarUsuarioRequestBody(string nickname, string nuevoNick, string nombre, string password, string email, int conectado) {
            this.nickname = nickname;
            this.nuevoNick = nuevoNick;
            this.nombre = nombre;
            this.password = password;
            this.email = email;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class modificarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="modificarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.modificarUsuarioResponseBody Body;
        
        public modificarUsuarioResponse() {
        }
        
        public modificarUsuarioResponse(NavalWarsCliente.ServiceReference1.modificarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class modificarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool modificarUsuarioResult;
        
        public modificarUsuarioResponseBody() {
        }
        
        public modificarUsuarioResponseBody(bool modificarUsuarioResult) {
            this.modificarUsuarioResult = modificarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioNickRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuarioNick", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.buscarUsuarioNickRequestBody Body;
        
        public buscarUsuarioNickRequest() {
        }
        
        public buscarUsuarioNickRequest(NavalWarsCliente.ServiceReference1.buscarUsuarioNickRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioNickRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public buscarUsuarioNickRequestBody() {
        }
        
        public buscarUsuarioNickRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioNickResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuarioNickResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.buscarUsuarioNickResponseBody Body;
        
        public buscarUsuarioNickResponse() {
        }
        
        public buscarUsuarioNickResponse(NavalWarsCliente.ServiceReference1.buscarUsuarioNickResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioNickResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool buscarUsuarioNickResult;
        
        public buscarUsuarioNickResponseBody() {
        }
        
        public buscarUsuarioNickResponseBody(bool buscarUsuarioNickResult) {
            this.buscarUsuarioNickResult = buscarUsuarioNickResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addjuegosUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addjuegosUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.addjuegosUsuarioRequestBody Body;
        
        public addjuegosUsuarioRequest() {
        }
        
        public addjuegosUsuarioRequest(NavalWarsCliente.ServiceReference1.addjuegosUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addjuegosUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nickOp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int uniDespl;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int uniSobrev;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int uniDestru;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int gano;
        
        public addjuegosUsuarioRequestBody() {
        }
        
        public addjuegosUsuarioRequestBody(string nickUsuario, string nickOp, int uniDespl, int uniSobrev, int uniDestru, int gano) {
            this.nickUsuario = nickUsuario;
            this.nickOp = nickOp;
            this.uniDespl = uniDespl;
            this.uniSobrev = uniSobrev;
            this.uniDestru = uniDestru;
            this.gano = gano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addjuegosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addjuegosUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.addjuegosUsuarioResponseBody Body;
        
        public addjuegosUsuarioResponse() {
        }
        
        public addjuegosUsuarioResponse(NavalWarsCliente.ServiceReference1.addjuegosUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addjuegosUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool addjuegosUsuarioResult;
        
        public addjuegosUsuarioResponseBody() {
        }
        
        public addjuegosUsuarioResponseBody(bool addjuegosUsuarioResult) {
            this.addjuegosUsuarioResult = addjuegosUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarJuegosUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarJuegosUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioRequestBody Body;
        
        public eliminarJuegosUsuarioRequest() {
        }
        
        public eliminarJuegosUsuarioRequest(NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarJuegosUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idJuego;
        
        public eliminarJuegosUsuarioRequestBody() {
        }
        
        public eliminarJuegosUsuarioRequestBody(string nickUsuario, string idJuego) {
            this.nickUsuario = nickUsuario;
            this.idJuego = idJuego;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarJuegosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarJuegosUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioResponseBody Body;
        
        public eliminarJuegosUsuarioResponse() {
        }
        
        public eliminarJuegosUsuarioResponse(NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarJuegosUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool eliminarJuegosUsuarioResult;
        
        public eliminarJuegosUsuarioResponseBody() {
        }
        
        public eliminarJuegosUsuarioResponseBody(bool eliminarJuegosUsuarioResult) {
            this.eliminarJuegosUsuarioResult = eliminarJuegosUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarJuegosUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarJuegosUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioRequestBody Body;
        
        public ModificarJuegosUsuarioRequest() {
        }
        
        public ModificarJuegosUsuarioRequest(NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarJuegosUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idJuego;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nickOp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int uniDespla;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int uniSobrev;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int uniDestru;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int gano;
        
        public ModificarJuegosUsuarioRequestBody() {
        }
        
        public ModificarJuegosUsuarioRequestBody(string nickUsuario, string idJuego, string nickOp, int uniDespla, int uniSobrev, int uniDestru, int gano) {
            this.nickUsuario = nickUsuario;
            this.idJuego = idJuego;
            this.nickOp = nickOp;
            this.uniDespla = uniDespla;
            this.uniSobrev = uniSobrev;
            this.uniDestru = uniDestru;
            this.gano = gano;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModificarJuegosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModificarJuegosUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioResponseBody Body;
        
        public ModificarJuegosUsuarioResponse() {
        }
        
        public ModificarJuegosUsuarioResponse(NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ModificarJuegosUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ModificarJuegosUsuarioResult;
        
        public ModificarJuegosUsuarioResponseBody() {
        }
        
        public ModificarJuegosUsuarioResponseBody(bool ModificarJuegosUsuarioResult) {
            this.ModificarJuegosUsuarioResult = ModificarJuegosUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : NavalWarsCliente.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<NavalWarsCliente.ServiceReference1.Service1Soap>, NavalWarsCliente.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.HelloWorldResponse NavalWarsCliente.ServiceReference1.Service1Soap.HelloWorld(NavalWarsCliente.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            NavalWarsCliente.ServiceReference1.HelloWorldRequest inValue = new NavalWarsCliente.ServiceReference1.HelloWorldRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.HelloWorldRequestBody();
            NavalWarsCliente.ServiceReference1.HelloWorldResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.insertarUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.insertarUsuario(NavalWarsCliente.ServiceReference1.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public bool insertarUsuario(string nickname, string nombre, string password, string email, int conectado) {
            NavalWarsCliente.ServiceReference1.insertarUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.insertarUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.insertarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            NavalWarsCliente.ServiceReference1.insertarUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).insertarUsuario(inValue);
            return retVal.Body.insertarUsuarioResult;
        }
        
        public void generarArbol() {
            base.Channel.generarArbol();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.buscarUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.buscarUsuario(NavalWarsCliente.ServiceReference1.buscarUsuarioRequest request) {
            return base.Channel.buscarUsuario(request);
        }
        
        public bool buscarUsuario(string nickname, string password) {
            NavalWarsCliente.ServiceReference1.buscarUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.buscarUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.buscarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            NavalWarsCliente.ServiceReference1.buscarUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).buscarUsuario(inValue);
            return retVal.Body.buscarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.eliminarUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.eliminarUsuario(NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public bool eliminarUsuario(string nickname) {
            NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.eliminarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            NavalWarsCliente.ServiceReference1.eliminarUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).eliminarUsuario(inValue);
            return retVal.Body.eliminarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.obtenerInfoUsuario(NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioRequest request) {
            return base.Channel.obtenerInfoUsuario(request);
        }
        
        public NavalWarsCliente.ServiceReference1.ArrayOfString obtenerInfoUsuario(string nickname) {
            NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            NavalWarsCliente.ServiceReference1.obtenerInfoUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).obtenerInfoUsuario(inValue);
            return retVal.Body.obtenerInfoUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.modificarUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.modificarUsuario(NavalWarsCliente.ServiceReference1.modificarUsuarioRequest request) {
            return base.Channel.modificarUsuario(request);
        }
        
        public bool modificarUsuario(string nickname, string nuevoNick, string nombre, string password, string email, int conectado) {
            NavalWarsCliente.ServiceReference1.modificarUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.modificarUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.modificarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.nuevoNick = nuevoNick;
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            NavalWarsCliente.ServiceReference1.modificarUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).modificarUsuario(inValue);
            return retVal.Body.modificarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.buscarUsuarioNickResponse NavalWarsCliente.ServiceReference1.Service1Soap.buscarUsuarioNick(NavalWarsCliente.ServiceReference1.buscarUsuarioNickRequest request) {
            return base.Channel.buscarUsuarioNick(request);
        }
        
        public bool buscarUsuarioNick(string nickname) {
            NavalWarsCliente.ServiceReference1.buscarUsuarioNickRequest inValue = new NavalWarsCliente.ServiceReference1.buscarUsuarioNickRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.buscarUsuarioNickRequestBody();
            inValue.Body.nickname = nickname;
            NavalWarsCliente.ServiceReference1.buscarUsuarioNickResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).buscarUsuarioNick(inValue);
            return retVal.Body.buscarUsuarioNickResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.addjuegosUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.addjuegosUsuario(NavalWarsCliente.ServiceReference1.addjuegosUsuarioRequest request) {
            return base.Channel.addjuegosUsuario(request);
        }
        
        public bool addjuegosUsuario(string nickUsuario, string nickOp, int uniDespl, int uniSobrev, int uniDestru, int gano) {
            NavalWarsCliente.ServiceReference1.addjuegosUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.addjuegosUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.addjuegosUsuarioRequestBody();
            inValue.Body.nickUsuario = nickUsuario;
            inValue.Body.nickOp = nickOp;
            inValue.Body.uniDespl = uniDespl;
            inValue.Body.uniSobrev = uniSobrev;
            inValue.Body.uniDestru = uniDestru;
            inValue.Body.gano = gano;
            NavalWarsCliente.ServiceReference1.addjuegosUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).addjuegosUsuario(inValue);
            return retVal.Body.addjuegosUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.eliminarJuegosUsuario(NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioRequest request) {
            return base.Channel.eliminarJuegosUsuario(request);
        }
        
        public bool eliminarJuegosUsuario(string nickUsuario, string idJuego) {
            NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioRequestBody();
            inValue.Body.nickUsuario = nickUsuario;
            inValue.Body.idJuego = idJuego;
            NavalWarsCliente.ServiceReference1.eliminarJuegosUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).eliminarJuegosUsuario(inValue);
            return retVal.Body.eliminarJuegosUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.ModificarJuegosUsuario(NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioRequest request) {
            return base.Channel.ModificarJuegosUsuario(request);
        }
        
        public bool ModificarJuegosUsuario(string nickUsuario, string idJuego, string nickOp, int uniDespla, int uniSobrev, int uniDestru, int gano) {
            NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioRequestBody();
            inValue.Body.nickUsuario = nickUsuario;
            inValue.Body.idJuego = idJuego;
            inValue.Body.nickOp = nickOp;
            inValue.Body.uniDespla = uniDespla;
            inValue.Body.uniSobrev = uniSobrev;
            inValue.Body.uniDestru = uniDestru;
            inValue.Body.gano = gano;
            NavalWarsCliente.ServiceReference1.ModificarJuegosUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).ModificarJuegosUsuario(inValue);
            return retVal.Body.ModificarJuegosUsuarioResult;
        }
    }
}
