//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavalWarsCliente.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.HelloWorldResponse HelloWorld(NavalWarsCliente.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.insertarUsuarioResponse insertarUsuario(NavalWarsCliente.ServiceReference1.insertarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/generarArbol", ReplyAction="*")]
        void generarArbol();
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/buscarUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.buscarUsuarioResponse buscarUsuario(NavalWarsCliente.ServiceReference1.buscarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name nickname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarUsuario", ReplyAction="*")]
        NavalWarsCliente.ServiceReference1.eliminarUsuarioResponse eliminarUsuario(NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(NavalWarsCliente.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(NavalWarsCliente.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.insertarUsuarioRequestBody Body;
        
        public insertarUsuarioRequest() {
        }
        
        public insertarUsuarioRequest(NavalWarsCliente.ServiceReference1.insertarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int conectado;
        
        public insertarUsuarioRequestBody() {
        }
        
        public insertarUsuarioRequestBody(string nickname, string nombre, string password, string email, int conectado) {
            this.nickname = nickname;
            this.nombre = nombre;
            this.password = password;
            this.email = email;
            this.conectado = conectado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.insertarUsuarioResponseBody Body;
        
        public insertarUsuarioResponse() {
        }
        
        public insertarUsuarioResponse(NavalWarsCliente.ServiceReference1.insertarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool insertarUsuarioResult;
        
        public insertarUsuarioResponseBody() {
        }
        
        public insertarUsuarioResponseBody(bool insertarUsuarioResult) {
            this.insertarUsuarioResult = insertarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.buscarUsuarioRequestBody Body;
        
        public buscarUsuarioRequest() {
        }
        
        public buscarUsuarioRequest(NavalWarsCliente.ServiceReference1.buscarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public buscarUsuarioRequestBody() {
        }
        
        public buscarUsuarioRequestBody(string nickname, string password) {
            this.nickname = nickname;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class buscarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="buscarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.buscarUsuarioResponseBody Body;
        
        public buscarUsuarioResponse() {
        }
        
        public buscarUsuarioResponse(NavalWarsCliente.ServiceReference1.buscarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class buscarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool buscarUsuarioResult;
        
        public buscarUsuarioResponseBody() {
        }
        
        public buscarUsuarioResponseBody(bool buscarUsuarioResult) {
            this.buscarUsuarioResult = buscarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.eliminarUsuarioRequestBody Body;
        
        public eliminarUsuarioRequest() {
        }
        
        public eliminarUsuarioRequest(NavalWarsCliente.ServiceReference1.eliminarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nickname;
        
        public eliminarUsuarioRequestBody() {
        }
        
        public eliminarUsuarioRequestBody(string nickname) {
            this.nickname = nickname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class eliminarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="eliminarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public NavalWarsCliente.ServiceReference1.eliminarUsuarioResponseBody Body;
        
        public eliminarUsuarioResponse() {
        }
        
        public eliminarUsuarioResponse(NavalWarsCliente.ServiceReference1.eliminarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class eliminarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool eliminarUsuarioResult;
        
        public eliminarUsuarioResponseBody() {
        }
        
        public eliminarUsuarioResponseBody(bool eliminarUsuarioResult) {
            this.eliminarUsuarioResult = eliminarUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : NavalWarsCliente.ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<NavalWarsCliente.ServiceReference1.Service1Soap>, NavalWarsCliente.ServiceReference1.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.HelloWorldResponse NavalWarsCliente.ServiceReference1.Service1Soap.HelloWorld(NavalWarsCliente.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            NavalWarsCliente.ServiceReference1.HelloWorldRequest inValue = new NavalWarsCliente.ServiceReference1.HelloWorldRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.HelloWorldRequestBody();
            NavalWarsCliente.ServiceReference1.HelloWorldResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.insertarUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.insertarUsuario(NavalWarsCliente.ServiceReference1.insertarUsuarioRequest request) {
            return base.Channel.insertarUsuario(request);
        }
        
        public bool insertarUsuario(string nickname, string nombre, string password, string email, int conectado) {
            NavalWarsCliente.ServiceReference1.insertarUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.insertarUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.insertarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.nombre = nombre;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.conectado = conectado;
            NavalWarsCliente.ServiceReference1.insertarUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).insertarUsuario(inValue);
            return retVal.Body.insertarUsuarioResult;
        }
        
        public void generarArbol() {
            base.Channel.generarArbol();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.buscarUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.buscarUsuario(NavalWarsCliente.ServiceReference1.buscarUsuarioRequest request) {
            return base.Channel.buscarUsuario(request);
        }
        
        public bool buscarUsuario(string nickname, string password) {
            NavalWarsCliente.ServiceReference1.buscarUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.buscarUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.buscarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            inValue.Body.password = password;
            NavalWarsCliente.ServiceReference1.buscarUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).buscarUsuario(inValue);
            return retVal.Body.buscarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NavalWarsCliente.ServiceReference1.eliminarUsuarioResponse NavalWarsCliente.ServiceReference1.Service1Soap.eliminarUsuario(NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest request) {
            return base.Channel.eliminarUsuario(request);
        }
        
        public bool eliminarUsuario(string nickname) {
            NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest inValue = new NavalWarsCliente.ServiceReference1.eliminarUsuarioRequest();
            inValue.Body = new NavalWarsCliente.ServiceReference1.eliminarUsuarioRequestBody();
            inValue.Body.nickname = nickname;
            NavalWarsCliente.ServiceReference1.eliminarUsuarioResponse retVal = ((NavalWarsCliente.ServiceReference1.Service1Soap)(this)).eliminarUsuario(inValue);
            return retVal.Body.eliminarUsuarioResult;
        }
    }
}
